### ISSUE TITLE
Doesn't seem to work often?

### ISSUE THREAD

**Issue by Jiur13** [tremwil/SteamP2PInfo#10]
I've followed all the instructions given to run this, and yet the program very rarely detects people. I've summoned about 20 different people now and it's only worked twice.

![eldenring_IvW7EanARj](https://user-images.githubusercontent.com/66332803/164781859-215c1c98-2d5b-4568-b3d4-f00e7a7574ee.jpg)
![JIf8DyviMn](https://user-images.githubusercontent.com/66332803/164781868-83b3421c-3860-4215-9187-64eeac2c93ff.jpg)
![SteamP2PInfo_yubHckDGG9](https://user-images.githubusercontent.com/66332803/164781871-d65e924a-052c-4c3a-ad62-7052f453643f.jpg)

.

**Comment by tremwil** [comment]
This is a known bug. Essentially Steam doesn't flush the log file after each line, so sometimes peers are not detected. In my own experience it works almost 100% of the time, so I'm not exactly sure what governs the rate at which the log file is flushed. This will be fixed in the next update, which will use internal hooks inside the Steam process to identity peers.

**Comment by Jiur13** [comment]
I see, thanks for clarifying.
