### ISSUE TITLE
Peers getting detected in rare circumstances, not the other way around

### ISSUE THREAD

**Issue by Rembs** [tremwil/SteamP2PInfo#17]
FYI: I saw the "Peers not getting detected in rare circumstances" under known issues, but in my experience peers don't get detected 90% or more of the time.

**Comment by tremwil** [comment]
First off, which game are you using this for? If it's Elden Ring, are you hosting specifically? I heard reports that the peers don't get detected much more often if you're hosting rather than joining the session. It might be a flaw in the program that causes detected lobbies get dropped even if you're in them.

Since the current way to get lobbies (IPC file parsing) will be replaced by an internal steam p2p hook in the future (which will make the tool 100% reliable) and I'm currently on vacation, I won't bother trying to fix this particular issue but will gladly create a new release if someone does and submits a pull request.

**Comment by Rembs** [comment]
Using it for hosting in Elden Ring yes.
Looking forward to the internal p2p hook!
Have a good time on vacation!

**Comment by angelosnikoloulo** [comment]
@tremwil I would love to help on replacing the the log parsing with the internal steam p2p hook you mentioned, however I couldn't find any relevant information on how to do this, is this possible to do with the steamworks library?, if you could you point me to the right direction I can try and make a pr to change this

**Comment by tremwil** [comment]
Fixed in 1.1.0
