### ISSUE TITLE
Overlay shows players, but nothing in "Recently Played With"

### ISSUE THREAD

**Issue by supersaiyansubtlety** [tremwil/SteamP2PInfo#23]
Using it for elden ring, invading.

**Comment by tremwil** [comment]
This feature should not be needed anymore, as Elden Ring adds the players you encounter to the Steam recently played list since update 1.04 (if I recall correctly). Where are you looking for this list? There are multiple places to access it from the Steam UI, but I did hear that one or more of them do not work properly. I personally access it from the Steam overlay while playing, and it works fine.

**Comment by supersaiyansubtlety** [comment]
I click on add friends and it's an option in the left column.

I'll look into steam overlay.

**Comment by supersaiyansubtlety** [comment]
Overlay has recent players, thanks!
