### ISSUE TITLE
How to add players as friends? 

### ISSUE THREAD

**Issue by j-6-w3n7w027h** [tremwil/SteamP2PInfo#25]
Since there is no way to view recent players on PC without a workaround such as this, how do I add somebody I play with in game? I'm playing Elden Ring and SteamP2P works, I just don't know how to use the info to actually send a request to the right account.

**Comment by tremwil** [comment]
Actually I have to update the readme, as Elden Ring implemented the Steam recent players almost half a year ago now (update 1.04 if I recall correctly). 

While using the program, you can double click on a player's name in the main application (not the overlay!) to open the Steam overlay on their profile page and add them. Otherwise, open the Steam overlay yourself and click "view players" followed by "recent games".
