### ISSUE TITLE
Misses half of the player in Elden ring Arena

### ISSUE THREAD

**Issue by taoli0515** [tremwil/SteamP2PInfo#30]
Half of the player are missed from by the app - tested over multiple back to back arena session. The very first session almost never misses, which lead me to believe It might have to do with back to back queuing

**Comment by tremwil** [comment]
Hi, the reason for this is that the peer detection method currently isn't very reliable when you are the owner of your session's Steam lobby (in the arena, you should expect to be the lobby owner about 50% of the time). In non-arena multiplayer, that player is the host. 

I see 2 possible fixes for this problem:
- Return to the detection method used by my Dark Souls 3 tool, which involves periodically fetching the list of recently encountered players and checking for active P2P connections. I didn't do this at first because Elden Ring used to not add players on this list (until update 1.04).
- It may also be possible to fix this by using `log_matchmaking_callbacks` in the Steam console and making use of the LobbyChatUpdate callback dumps to find peers. 

I don't currently have time to work on this project, and one of the next ones I will be working on will be an Elden Ring specific tool that uses an internal Steam hook to provide detailed connection information and more (like player character names, rune levels, etc). However, if anyone is willing to implement these things and submit a PR, I will happily accept it.
