### ISSUE TITLE
Using program causes steam to disconnect from internet

### ISSUE THREAD

**Issue by redeemednorabbi** [tremwil/SteamP2PInfo#54]
Title. I know it's this program causing it because I didn't have any issues like this before I started using it. I know it's not my wifi going down because I can use the wifi on this pc for literally anything aside from steam, which randomly disconnects and stays that way for a long time. After no longer using this program steam hasn't randomly disconnected me even once. On top of all of this I've reinstalled steam twice over so I know the issue isn't stemming from steam itself.

Has anyone else noticed this issue? I love using this program to prepare for laggards in arena and to see how many people are in the session with me.

**Comment by tremwil** [comment]
It's not possible for this program to cause a particular application to lose internet connectivity (or affect connectivity in any way). The program subscribes to a Windows API that notifies it when network packets are sent/received by the network driver, along with some metadata about the packet. It cannot modify them or otherwise cause changes in how network traffic is routed. 

While it does make calls to Steam APIs, these likewise have no effect on whether Steam can connect to the Internet.
